const Companylogos = [
  { image: "/logos/ACCELYA.png", alt: "ACCELYA" },
  { image: "/logos/ACCENTURE.png", alt: "ACCENTURE" },
  { image: "/logos/ACROTREND.png", alt: "ACROTREND" },
  { image: "/logos/ALLERIN.png", alt: "ALLERIN" },
  { image: "/logos/AURIONPRO.png", alt: "AURIONPRO" },
  { image: "/logos/BITWISE.png", alt: "BITWISE" },
  { image: "/logos/BKT.png", alt: "BKT" },
  { image: "/logos/byjus.png", alt: "BYJU'S" },
  { image: "/logos/capgemini.jpg", alt: "Capgemini" },
  { image: "/logos/cognizant.jpg", alt: "Cognizant" },
  { image: "/logos/COGNIZANT.png", alt: "COGNIZANT" },
  { image: "/logos/DELOITTE.png", alt: "DELOITTE" },
  { image: "/logos/dhl.jpg", alt: "DHL" },
  { image: "/logos/DYSON.png", alt: "DYSON" },
  { image: "/logos/ELEATION.png", alt: "ELEATION" },
  { image: "/logos/ENDURANCE.png", alt: "ENDURANCE" },
  { image: "/logos/GODEREJ.png", alt: "GODREJ" },
  { image: "/logos/GRP.png", alt: "GRP" },
  { image: "/logos/goldman.jpg", alt: "Goldman Sachs" },
  { image: "/logos/HEXAWARE.png", alt: "HEXWARE" },
  { image: "/logos/Infosys.png", alt: "Infosys" },
  { image: "/logos/INFOYS.png", alt: "INFOYS" },
  { image: "/logos/JARO EDUCATION.png", alt: "JARO EDUCATION" },
  { image: "/logos/KPIT.png", alt: "KPIT" },
  { image: "/logos/LTI.png", alt: "LTI Mindtree" },
  { image: "/logos/MAJESCO.png", alt: "MAJESCO" },
  { image: "/logos/MERCE.png", alt: "MERCE" },
  { image: "/logos/MINDCRAFT.png", alt: "MINDCRAFT" },
  { image: "/logos/NEC.png", alt: "NEC" },
  { image: "/logos/NEOSOFT TECHNOLOGIES.png", alt: "NEOSOFT TECHNOLOGIES" },
  { image: "/logos/NEWGEN.png", alt: "NEWGEN" },
  { image: "/logos/NSE.png", alt: "NSE" },
  { image: "/logos/PINCLICK.png", alt: "PINCLICK" },
  { image: "/logos/Q SPIDER.png", alt: "QSPIDER" },
  { image: "/logos/QUALITY KIOS.png", alt: "QUALITY KIOS" },
  { image: "/logos/RELANCE RETAIL.png", alt: "RELANCE RETAIL" },
  { image: "/logos/RELIANCE INDUSTRIES LTD.png", alt: "RELIANCE INDUSTRIES LTD" },
  { image: "/logos/SANMAR.png", alt: "SANMAR" },
  { image: "/logos/SELEC.png", alt: "SELEC" },
  { image: "/logos/SUTHERLAND.png", alt: "SUTHERLAND" },
  { image: "/logos/tcs.jpg", alt: "TCS" },
  { image: "/logos/TOPPR.png", alt: "TOPPR" },
  { image: "/logos/TRILOGY.png", alt: "TRILOGY" },
  { image: "/logos/TSS.png", alt: "TSS" },
  { image: "/logos/UGAM.png", alt: "UGAM" },
  { image: "/logos/WIPRO.png", alt: "WIPRO" },
  { image: "/logos/WTW.png", alt: "WTW" },
  { image: "/logos/YOTTA.png", alt: "YOTTA" },
];
export default Companylogos;
